### ISSUE TITLE
include_lib uses deprecated functions?

### ISSUE THREAD

**Issue by ijcd** [qhool/quaff#6]
== Compilation error on file lib/exncurses_demo.ex ==
** (UndefinedFunctionError) undefined function: String.from_char_list!/1
    (elixir) String.from_char_list!([67, 97, 110, 39, 116, 32, 108, 111, 99, 97, 116, 101, 32, 104, 101, 97, 100, 101, 114, 32, 'deps/encurses/include/encurses.hrl', '\n', 32, 114, 101, 108, 97, 116, 105, 118, 101, 32, 116, 111, 58, 32, '/Users/ijcd/work/elixir/exncurses/lib', '\n', 32, 105, 110, 99, 108, 117, 100, 101, 32, 112, 97, 116, ...])
    lib/constants.ex:24: Quaff.Constants.CompileError.exception/1
    lib/constants.ex:181: Quaff.Constants.read_header/2
    lib/constants.ex:123: Quaff.Constants.get_constants/2
    expanding macro: Quaff.Constants.include/2
    lib/exncurses_demo.ex:7: ExncursesDemo (module)
    expanding macro: Quaff.Constants.include_lib/2
    lib/exncurses_demo.ex:7: ExncursesDemo (module)

**Comment by qhool** [comment]
Can you tell me the versions of elixir & erlang you're using?

**Comment by DerKastellan** [comment]
Hi, qhool.

Have the same problem.

I'm using Elixir 1.2.3.

Erlang:
$ cat /usr/local/lib/erlang/releases/RELEASES
[{release,"Erlang/OTP","18","7.2",
          [{kernel,"4.1.1","/usr/local/lib/erlang/lib/kernel-4.1.1"},
           {stdlib,"2.7","/usr/local/lib/erlang/lib/stdlib-2.7"},
           {sasl,"2.6.1","/usr/local/lib/erlang/lib/sasl-2.6.1"}],
          permanent}].

**Comment by DerKastellan** [comment]
@qhool 

Hello, Josh. I forgot to do a mention in my answer. Sorry.
